### PR TITLE
Support for Configuration panel

### PR DESCRIPTION
**Pull request by brandones**
esm-module-config needs to be updated with https://github.com/openmrs/openmrs-esm-module-config/pull/19

### CODE REVIEW

**Comment by brandones** [comment]
Screenshot from 2020-02-24 18-15-18

**Comment by brandones** [comment]
Being able to override the config in the devtools will be a future PR. As will displaying the source of each config value.

**Review by jonathandick — APPROVED** [review]
LGTM. I think you can move to PR rather than draft

**Comment by brandones** [comment]
Thanks JJ! It's a draft because it depends on https://github.com/openmrs/openmrs-esm-module-config/pull/19 . It is not ready to be merged.

**Pull request merged**
