### PR TITLE
Fix backend modules console warning

### PR DESCRIPTION
**Pull request by donaldkibet**
This PR Fixes console warning on the backend render method on unique keys warning

Screenshot from 2020-03-11 11-43-48

### CODE REVIEW

**Review by brandones — COMMENTED** [review]
Code looks good; can you post a screenshot of what it looks like now?

**Comment by donaldkibet** [comment]
> Code looks good; can you post a screenshot of what it looks like now?

Screenshot from 2020-03-12 00-11-37

clean console

**Comment by brandones** [comment]
Sorry I wasn't clear -- I meant the devtools console itself, what does it look like when it displays missing or incorrect modules? It looks like you've changed the layout and view logic a bunch. Would be nice to see what it looks like.

**Review by tendomart — COMMENTED** [review]
I found it clear too.

**Comment by donaldkibet** [comment]
> Sorry I wasn't clear -- I meant the devtools console itself, what does it look like when it displays missing or incorrect modules? It looks like you've changed the layout and view logic a bunch. Would be nice to see what it looks like.

Screenshot from 2020-03-12 09-38-43

**Review by brandones — APPROVED** [review]
Excellent, thank you!

**Pull request merged**
